# TODO - Need to comment out `build` blocks as a workaround to allow `docker-compose up`
# to work until we can add cache_from when docker-compose 1.12.0 is GA (and version 3.2 is supported)
# Is there a similar thing we can do for `volumes`?

version: '3'

services:
  mongo:
    image: mongo:3.2
    container_name: tidepool_mongo
    volumes:
      - ${TP_MONGO_DATA_DIR:-mongo-data}:/data/db
    networks:
     - back-tier
    # So that we can get to the database from the host
    ports:
      - '27017:27017'

  hakken:
    image: tidepool/hakken
    container_name: hakken
    # volumes:
    #   - $TP_HAKKEN_DIR:/app
    environment:
      NODE_ENV: development
    expose:
      - '8000'
    networks:
      - back-tier

  highwater:
    image: tidepool/highwater
    container_name: highwater
    # volumes:
    #   - $TP_HIGHWATER_DIR:/app
    links:
      - hakken
    environment:
      NODE_ENV: development
    expose:
      - '9191'
    networks:
      - back-tier

  hydrophone:
    image: tidepool/hydrophone
    container_name: hydrophone
    # build: $TP_HYDROPHONE_DIR
    # volumes:
    #   - $TP_HYDROPHONE_DIR:/go/src/github.com/tidepool-org/hydrophone
    #   - hydrophone-config:/go/src/github.com/tidepool-org/hydrophone/config
    links:
      - mongo
      - hakken
      - gatekeeper
      - seagull
      - highwater
      - shoreline
    expose:
      - '9157'
    networks:
      - back-tier

  seagull:
    image: tidepool/seagull
    container_name: seagull
    # volumes:
    #   - $TP_SEAGULL_DIR:/app
    environment:
      NODE_ENV: development
    links:
      - hakken
      - mongo
    expose:
      - '9120'
    networks:
      - back-tier

  jellyfish:
    image: tidepool/jellyfish
    container_name: jellyfish
    # volumes:
    #   - $TP_JELLYFISH_DIR:/app
    environment:
      NODE_ENV: development
    links:
      - hakken
      - mongo
    expose:
      - '9122'
    networks:
      - back-tier
      - front-tier
    ports:
      - '9122:9122'

  auth:
    image: tidepool/auth
    container_name: auth
    # build:
    #  context: $TP_PLATFORM_DIR
    #  dockerfile: Dockerfile.auth
    links:
      - hakken
      - mongo
      - styx
    expose:
      - '9222'
    networks:
      - back-tier
      - front-tier
    ports:
      - '9222:9222'

  data:
    image: tidepool/data
    container_name: data
    # build:
    #  context: $TP_PLATFORM_DIR
    #  dockerfile: Dockerfile.data
    links:
      - hakken
      - mongo
      - styx
      - user
    expose:
      - '9220'
    networks:
      - back-tier
      - front-tier
    ports:
      - '9220:9220'

  notification:
    image: tidepool/notification
    container_name: notification
    # build:
    #  context: $TP_PLATFORM_DIR
    #  dockerfile: Dockerfile.notification
    links:
      - hakken
      - mongo
      - styx
    expose:
      - '9223'
    networks:
      - back-tier
      - front-tier
    ports:
      - '9223:9223'

  task:
    image: tidepool/task
    container_name: task
    # build:
    #  context: $TP_PLATFORM_DIR
    #  dockerfile: Dockerfile.task
    links:
      - hakken
      - mongo
      - styx
      - auth
    expose:
      - '9224'
    networks:
      - back-tier
      - front-tier
    ports:
      - '9224:9224'

  user:
    image: tidepool/user
    container_name: user
    # build:
    #  context: $TP_PLATFORM_DIR
    #  dockerfile: Dockerfile.user
    links:
      - hakken
      - mongo
      - styx
    expose:
      - '9221'
    networks:
      - back-tier
      - front-tier
    ports:
      - '9221:9221'

  # tools:
  #   image: tidepool/tools
  #   container_name: tools
  #   # build:
  #   #  context: $TP_PLATFORM_DIR
  #   #  dockerfile: Dockerfile.tools
  #   # volumes:
  #   # - $TP_PLATFORM_DIR:/go/src/github.com/tidepool-org/platform
  #   # - platform-config:/go/src/github.com/tidepool-org/platform/_config
  #   links:
  #     - hakken
  #     - mongo
  #     - styx
  #     - userservices
  #     - dataservices
  #   networks:
  #     - back-tier
  #     - front-tier

  # viz:
  #   image: tidepool/viz
  #   container_name: viz
  #   volumes:
  #     - $TP_VIZ_DIR:/app:cached
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - '8081:8081'

  blip:
    image: tidepool/blip
    container_name: blip
    # volumes:
    #   - $TP_BLIP_DIR:/app:cached
    #   - $TP_VIZ_DIR:/@tidepool/viz:cached
    #   - $TP_TIDELINE_DIR:/tideline:cached
    #   - $TP_TIDEPOOL_PLATFORM_CLIENT_DIR:/tidepool-platform-client:cached
    environment:
      NODE_ENV: development
      DEV_TOOLS: ${DEV_TOOLS:-true}
    depends_on:
      - styx
      - shoreline
      - seagull
      - jellyfish
      - gatekeeper
    networks:
      - back-tier
      - front-tier
    ports:
      - '3000:3000'

  message-api:
    image: tidepool/message-api
    container_name: message-api
    # volumes:
    #   - $TP_MESSAGE_API_DIR:/app
    environment:
      NODE_ENV: development
    links:
      - hakken
      - mongo
    expose:
      - '9119'
    networks:
      - back-tier

  styx:
    image: tidepool/styx
    container_name: styx
    # volumes:
    #   - $TP_STYX_DIR:/app
    environment:
      NODE_ENV: development
    links:
      - hakken
      - shoreline
      - seagull
      - jellyfish
      - gatekeeper
    expose:
      - '8009'
      - '8010'
    networks:
      - back-tier
      - front-tier
    ports:
      - '8009:8009'
      - '8010:8010'

  gatekeeper:
    image: tidepool/gatekeeper
    container_name: gatekeeper
    # volumes:
    #   - $TP_GATEKEEPER_DIR:/app
    environment:
      NODE_ENV: development
    links:
      - mongo
      - hakken
    expose:
      - '9123'
    networks:
      - back-tier

  shoreline:
    image: tidepool/shoreline
    container_name: shoreline
    # build: $TP_SHORELINE_DIR
    links:
      - mongo
      - hakken
      - highwater
      - gatekeeper
    expose:
      - '9107'
    networks:
      - back-tier

  tide-whisperer:
    image: tidepool/tide-whisperer
    container_name: tide-whisperer
    # build: $TP_TIDE_WHISPERER_DIR
    links:
      - mongo
      - hakken
      - gatekeeper
      - seagull
      - shoreline
    expose:
      - '9127'
    networks:
      - back-tier

volumes:
  mongo-data:
  hydrophone-config:
  platform-config:

networks:
  front-tier:
  back-tier:
